#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Project01.Resource", IsApplication=true)]

namespace Project01
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int theme_devicedefault_background = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int TutorialTone1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int TutorialTone2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int TutorialTone3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int TutorialTone4 = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public const int audioPlot = 2131230726;
			
			// aapt resource value: 0x7f08000c
			public const int back = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int checkedTextView1 = 2131230729;
			
			// aapt resource value: 0x7f080010
			public const int exampleMode = 2131230736;
			
			// aapt resource value: 0x7f080002
			public const int language = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int listView1 = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int listen_button = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int playWord = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int record_button = 2131230728;
			
			// aapt resource value: 0x7f08000d
			public const int searchView1 = 2131230733;
			
			// aapt resource value: 0x7f080001
			public const int textView1 = 2131230721;
			
			// aapt resource value: 0x7f08000b
			public const int textView2 = 2131230731;
			
			// aapt resource value: 0x7f080005
			public const int toneNumber = 2131230725;
			
			// aapt resource value: 0x7f08000f
			public const int tutorial = 2131230735;
			
			// aapt resource value: 0x7f08000a
			public const int tutorial_gallery = 2131230730;
			
			// aapt resource value: 0x7f08000e
			public const int wordList = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LanguageSelect = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Lesson = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ToneTutorial01 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int WordSelect = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int F1mother = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int F2numb = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int F3horse = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int F4scold = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int forget = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int test = 2130968581;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Custom = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
